### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by vihanb** [covfefe-lang/covfefe#1]
Logo suggestion:

<img width="633" alt="screen shot 2017-06-01 at 2 36 55 pm" src="https://cloud.githubusercontent.com/assets/15314511/26701941/d0282328-46d7-11e7-9367-f1122e357760.png">

It's obviously an "upside-down" L (definitely not fake news), where L is for "Language" :P

**Comment by christopherpeart** [comment]
It think it looks good. Perhaps the words fake news crossed out in the gap?

**Comment by anna328p** [comment]
Trump hair? Nice.

I think it should stay as is.

**Comment by christopherpeart** [comment]
This is status-complete
